In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import sys

sys.path.append("../src")

from sentence_transformers import SentenceTransformer
from data_loader import load_candidates
from job_representation import build_job_description
from retrieval import Retriever
from ranking import Ranker

# Load model only once
embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

retriever = Retriever(embedding_model)
ranker = Ranker(embedding_model)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [4]:

from data_loader import load_candidates

candidates = load_candidates(
    "../data/candidates.jsonl",
    limit=100
)

print(len(candidates))

100

In [5]:
from docx import Document
from job_representation import build_job_description

doc = Document("../India_Runs_Hackathon/job_description.docx")

jd_text = "\n".join(
    para.text
    for para in doc.paragraphs
)

job = build_job_description(jd_text)

In [6]:
ranker.build_requirement_embeddings(job)

ranker.build_experience_embeddings(candidates)

In [7]:
from explanation import ExplanationGenerator

In [8]:
rankings = ranker.rank_candidates(
    job,
    candidates
)

In [8]:
print(rankings[0].keys())

dict_keys(['candidate', 'candidate_id', 'final_score', 'evidence_score', 'skill_score', 'experience_score', 'behavior_score'])

In [9]:
print(rankings[0]["candidate"])

Candidate(candidate_id='CAND_0000031', retrieval_document="Summary: Machine learning engineer with 6.0 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shipping real systems and seeing what holds up under production load. Open to senior IC roles in applied ML or AI engineering, ideally at product companies where I'd own a meaningful piece of the ML stack.\nHeadline: Recommendation Systems Engineer | Search, Ranking & Retrieval\nSkills: Go, MLflow, FAISS, Pinecone, Angular, Image Classification, Machine Learning, Speech Recognition, BentoML, MLOps, Embeddings, Information Retrieval, Hugging Face Transformers, Feature Engineering, Sentence Transformers, scikit-learn, Marketing\nEducation: M.Tech Computer Engineering\nCompany: Swiggy\nExperience Title: Recommendation Systems Engineer\nExperience Description: Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.\nCompany: Mad Street Den\nExperience Title: Search Engineer\nExperience Description: Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.\nCompany: Uber\nExperience Title: NLP Engineer\nExperience Description: Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.\nCompany: Zomato\nExperience Title: Applied ML Engineer\nExperience Description: Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow. Most of the work was infrastructure and data quality — the modeling part was almost the easy bit. Final model improved revenue-per-search by 12%.", experiences=[Experience(company='Swiggy', title='Recommendation Systems Engineer', duration_months=14, is_current=True, industry='Food Delivery', company_size='5001-10000', description="Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.", evidence_text="Recommendation Systems Engineer. Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.", embedding=None), Experience(company='Mad Street Den', title='Search Engineer', duration_months=16, is_current=False, industry='AI/ML', company_size='201-500', description="Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.", evidence_text="Search Engineer. Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.", embedding=None), Experience(company='Uber', title='NLP Engineer', duration_months=27, is_current=False, industry='Transportation', company_size='10001+', description="Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.", evidence_text="NLP Engineer. Trained and shipped multiple ranking models for our product's discovery feed using XGBoost and LightGBM. Designed features across three families: content metadata, user behavior signals, and item engagement history. Owned the offline-online correlation analysis that determined which offline metrics actually predicted A/B test outcomes. Worked closely with PMs to define the optimization target (click-through vs. dwell time vs. downstream conversion) — that work was as important as the modeling itself.", embedding=None), Experience(company='Zomato', title='Applied ML Engineer', duration_months=13, is_current=False, industry='Food Delivery', company_size='5001-10000', description='Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow. Most of the work was infrastructure and data quality — the modeling part was almost the easy bit. Final model improved revenue-per-search by 12%.', evidence_text='Applied ML Engineer. Owned the ranking layer for an e-commerce search product, evolving it from a hand-tuned scoring function to a learning-to-rank model over 9 months. Designed the relevance labeling pipeline (mix of click-through data and explicit human judgments), the feature pipeline, and the training/eval workflow. Most of the work was infrastructure and data quality — the modeling part was almost the easy bit. Final model improved revenue-per-search by 12%.', embedding=None)], skills=[Skill(name='Go', proficiency='intermediate', endorsements=7, duration_months=19), Skill(name='MLflow', proficiency='advanced', endorsements=59, duration_months=21), Skill(name='FAISS', proficiency='advanced', endorsements=19, duration_months=35), Skill(name='Pinecone', proficiency='expert', endorsements=34, duration_months=88), Skill(name='Angular', proficiency='beginner', endorsements=4, duration_months=18), Skill(name='Image Classification', proficiency='advanced', endorsements=56, duration_months=28), Skill(name='Machine Learning', proficiency='advanced', endorsements=43, duration_months=23), Skill(name='Speech Recognition', proficiency='intermediate', endorsements=14, duration_months=24), Skill(name='BentoML', proficiency='intermediate', endorsements=6, duration_months=14), Skill(name='MLOps', proficiency='intermediate', endorsements=15, duration_months=36), Skill(name='Embeddings', proficiency='expert', endorsements=48, duration_months=60), Skill(name='Information Retrieval', proficiency='expert', endorsements=2, duration_months=84), Skill(name='Hugging Face Transformers', proficiency='expert', endorsements=18, duration_months=36), Skill(name='Feature Engineering', proficiency='advanced', endorsements=38, duration_months=26), Skill(name='Sentence Transformers', proficiency='expert', endorsements=16, duration_months=69), Skill(name='scikit-learn', proficiency='advanced', endorsements=41, duration_months=60), Skill(name='Marketing', proficiency='intermediate', endorsements=11, duration_months=36)], signals={'profile_completeness_score': 83.4, 'signup_date': '2026-01-28', 'last_active_date': '2026-05-24', 'open_to_work_flag': True, 'profile_views_received_30d': 194, 'applications_submitted_30d': 2, 'recruiter_response_rate': 0.91, 'avg_response_time_hours': 76.1, 'skill_assessment_scores': {'MLflow': 75.1, 'FAISS': 68.4, 'Pinecone': 53.6, 'Image Classification': 57.1}, 'connection_count': 832, 'endorsements_received': 177, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 27.3, 'max': 60.2}, 'preferred_work_mode': 'flexible', 'willing_to_relocate': True, 'github_activity_score': 32.6, 'search_appearance_30d': 778, 'saved_by_recruiters_30d': 13, 'interview_completion_rate': 0.6, 'offer_acceptance_rate': 0.38, 'verified_email': False, 'verified_phone': True, 'linkedin_connected': False}, metadata={'num_skills': 17, 'num_jobs': 4, 'num_education': 1, 'years_of_experience': 6.0})

In [1]:
explainer = ExplanationGenerator()

NameError: name 'ExplanationGenerator' is not defined

In [16]:
#testing exp generator
from submission import generate_submission

submission = generate_submission(
    job,
    candidates,
    ranker,
    explainer
)

submission.head()

   candidate_id  rank                                          reasoning
0  CAND_0000031     1  Production experience in recommendation system...
1  CAND_0000082     2  Relevant production engineering experience. Ke...
2  CAND_0000063     3  Relevant production engineering experience. Ke...
3  CAND_0000016     4  Relevant production engineering experience. Ke...
4  CAND_0000001     5  Relevant production engineering experience. Ke...

In [13]:
rankings = ranker.rank_candidates(
    job,
    candidates
)

print(len(rankings))

100

In [14]:
top_candidates = rankings[:100]

print(len(top_candidates))

100

In [15]:
print(len(rows))

NameError: name 'rows' is not defined

In [11]:
candidate = next(
    c for c in candidates
    if c.candidate_id == "CAND_0000001"
)

ranking = next(
    r for r in rankings
    if r["candidate_id"] == "CAND_0000001"
)

print(
    explainer.generate_reasoning(
        job,
        candidate,
        ranking
    )
)

Relevant production engineering experience. 6.9 years of experience matches the preferred range. Behavioral signals indicate actively seeking opportunities.

In [12]:
from submission import generate_submission

submission = generate_submission(
    job,
    candidates,
    ranker,
    explainer
)

submission.head()

   candidate_id   score                                          reasoning
0  CAND_0000031  0.4782  Production experience in recommendation system...

In [6]:
#score exp
for cid in [
    "CAND_0000031",
    "CAND_0000082",
    "CAND_0000001",
    "CAND_0000074"
]:

    candidate = next(
        c for c in candidates
        if c.candidate_id == cid
    )

    print(
        cid,
        candidate.metadata["years_of_experience"],
        ranker._score_experience(job, candidate)
    )

CAND_0000031 6.0 1.0
CAND_0000082 7.4 1.0
CAND_0000001 6.9 1.0
CAND_0000074 1.9 0.38

In [7]:
candidate = next(
    c for c in candidates
    if c.candidate_id == "CAND_0000031"
)

print(candidate.signals)

{'profile_completeness_score': 83.4, 'signup_date': '2026-01-28', 'last_active_date': '2026-05-24', 'open_to_work_flag': True, 'profile_views_received_30d': 194, 'applications_submitted_30d': 2, 'recruiter_response_rate': 0.91, 'avg_response_time_hours': 76.1, 'skill_assessment_scores': {'MLflow': 75.1, 'FAISS': 68.4, 'Pinecone': 53.6, 'Image Classification': 57.1}, 'connection_count': 832, 'endorsements_received': 177, 'notice_period_days': 60, 'expected_salary_range_inr_lpa': {'min': 27.3, 'max': 60.2}, 'preferred_work_mode': 'flexible', 'willing_to_relocate': True, 'github_activity_score': 32.6, 'search_appearance_30d': 778, 'saved_by_recruiters_30d': 13, 'interview_completion_rate': 0.6, 'offer_acceptance_rate': 0.38, 'verified_email': False, 'verified_phone': True, 'linkedin_connected': False}

In [8]:
#score signals tets 
for cid in [
    "CAND_0000031",
    "CAND_0000082",
    "CAND_0000001",
    "CAND_0000074"
]:

    candidate = next(
        c for c in candidates
        if c.candidate_id == cid
    )

    print(
        cid,
        round(
            ranker._score_behavior(candidate),
            3
        )
    )

CAND_0000031 0.793
CAND_0000082 0.641
CAND_0000001 0.591
CAND_0000074 0.379

In [13]:
results = ranker.rank_candidates(
    job,
    candidates
)

results[:10]

[{'candidate_id': 'CAND_0000031',
  'final_score': 0.4781632833373547,
  'evidence_score': 0.30928656667470933,
  'skill_score': 0.1,
  'experience_score': 1.0,
  'behavior_score': 0.7926},
 {'candidate_id': 'CAND_0000082',
  'final_score': 0.3926870748651028,
  'evidence_score': 0.18113414973020553,
  'skill_score': 0.16,
  'experience_score': 1.0,
  'behavior_score': 0.6406000000000001},
 {'candidate_id': 'CAND_0000063',
  'final_score': 0.3593620457775891,
  'evidence_score': 0.12292409155517817,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.7395},
 {'candidate_id': 'CAND_0000016',
  'final_score': 0.35622325835585594,
  'evidence_score': 0.13242651671171188,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.7000500000000001},
 {'candidate_id': 'CAND_0000001',
  'final_score': 0.34599858152270313,
  'evidence_score': 0.15569716304540634,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.59075},
 {'candidate_id': 'CAND_0000093',
  'final_score': 0.3401156597036123,
  'evidence_score': 0.14547131940722466,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.5869},
 {'candidate_id': 'CAND_0000033',
  'final_score': 0.3385262073361874,
  'evidence_score': 0.13747241467237473,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.59895},
 {'candidate_id': 'CAND_0000024',
  'final_score': 0.3334752778744698,
  'evidence_score': 0.1656305557489395,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.5033000000000001},
 {'candidate_id': 'CAND_0000026',
  'final_score': 0.3326056933808327,
  'evidence_score': 0.17275138676166535,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.48115},
 {'candidate_id': 'CAND_0000042',
  'final_score': 0.33237486749351025,
  'evidence_score': 0.1842297349870205,
  'skill_score': 0.0,
  'experience_score': 1.0,
  'behavior_score': 0.45130000000000003}]

In [14]:
results = ranker.rank_candidates(job, candidates)

print(results[:10])

[{'candidate_id': 'CAND_0000031', 'final_score': 0.4781632833373547, 'evidence_score': 0.30928656667470933, 'skill_score': 0.1, 'experience_score': 1.0, 'behavior_score': 0.7926}, {'candidate_id': 'CAND_0000082', 'final_score': 0.3926870748651028, 'evidence_score': 0.18113414973020553, 'skill_score': 0.16, 'experience_score': 1.0, 'behavior_score': 0.6406000000000001}, {'candidate_id': 'CAND_0000063', 'final_score': 0.3593620457775891, 'evidence_score': 0.12292409155517817, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.7395}, {'candidate_id': 'CAND_0000016', 'final_score': 0.35622325835585594, 'evidence_score': 0.13242651671171188, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.7000500000000001}, {'candidate_id': 'CAND_0000001', 'final_score': 0.34599858152270313, 'evidence_score': 0.15569716304540634, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.59075}, {'candidate_id': 'CAND_0000093', 'final_score': 0.3401156597036123, 'evidence_score': 0.14547131940722466, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.5869}, {'candidate_id': 'CAND_0000033', 'final_score': 0.3385262073361874, 'evidence_score': 0.13747241467237473, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.59895}, {'candidate_id': 'CAND_0000024', 'final_score': 0.3334752778744698, 'evidence_score': 0.1656305557489395, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.5033000000000001}, {'candidate_id': 'CAND_0000026', 'final_score': 0.3326056933808327, 'evidence_score': 0.17275138676166535, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.48115}, {'candidate_id': 'CAND_0000042', 'final_score': 0.33237486749351025, 'evidence_score': 0.1842297349870205, 'skill_score': 0.0, 'experience_score': 1.0, 'behavior_score': 0.45130000000000003}]

In [ ]:
import importlib
import ranking

importlib.reload(ranking)

from ranking import Ranker

In [19]:
ranker = Ranker(embedding_model)

In [6]:
#score skill test
candidate = next(
    c for c in candidates
    if c.candidate_id == "CAND_0000031"
)

print(
    ranker._score_skills(
        job,
        candidate
    )
)

0.1

In [7]:
for cid in [
    "CAND_0000031",
    "CAND_0000082",
    "CAND_0000001",
    "CAND_0000074"
]:

    candidate = next(
        c for c in candidates
        if c.candidate_id == cid
    )

    print(
        cid,
        round(
            ranker._score_skills(job, candidate),
            3
        )
    )

CAND_0000031 0.1
CAND_0000082 0.16
CAND_0000001 0.0
CAND_0000074 0.28

In [6]:
#metadata test
candidate = candidates[0]

print(candidate.metadata)

{'num_skills': 17, 'num_jobs': 2, 'num_education': 1, 'years_of_experience': 6.9}

In [ ]:
#score evidence test
andidate = next(
    c for c in candidates
    if c.candidate_id == "CAND_0000031"
)

score = ranker._score_evidence(
    job,
    candidate
)

print(score)

retrieval systems         Weight=3.0 Best=0.000
retrieval systems         Weight=3.0 Best=0.339
retrieval systems         Weight=3.0 Best=0.369
retrieval systems         Weight=3.0 Best=0.369
1.1072203516960144
3.0
ranking systems           Weight=3.0 Best=0.000
ranking systems           Weight=3.0 Best=0.448
ranking systems           Weight=3.0 Best=0.448
ranking systems           Weight=3.0 Best=0.448
2.4500079452991486
6.0
recommendation systems    Weight=3.0 Best=0.000
recommendation systems    Weight=3.0 Best=0.501
recommendation systems    Weight=3.0 Best=0.501
recommendation systems    Weight=3.0 Best=0.501
3.953246980905533
9.0
search systems            Weight=3.0 Best=0.000
search systems            Weight=3.0 Best=0.331
search systems            Weight=3.0 Best=0.417
search systems            Weight=3.0 Best=0.417
5.204311966896057
12.0
embeddings                Weight=2.5 Best=0.000
embeddings                Weight=2.5 Best=0.101
embeddings                Weight=2.5 Best=0.101
embeddings                Weight=2.5 Best=0.149
5.595610499382019
14.5
vector databases          Weight=2.5 Best=0.000
vector databases          Weight=2.5 Best=0.215
vector databases          Weight=2.5 Best=0.235
vector databases          Weight=2.5 Best=0.235
6.182717591524124
17.0
python                    Weight=1.5 Best=0.000
python                    Weight=1.5 Best=0.148
python                    Weight=1.5 Best=0.148
python                    Weight=1.5 Best=0.176
6.446440182626247
18.5
llms                      Weight=1.5 Best=0.000
llms                      Weight=1.5 Best=0.203
llms                      Weight=1.5 Best=0.203
llms                      Weight=1.5 Best=0.203
6.7515652403235435
20.0
fine-tuning               Weight=1.0 Best=0.000
fine-tuning               Weight=1.0 Best=0.228
fine-tuning               Weight=1.0 Best=0.228
fine-tuning               Weight=1.0 Best=0.228
7.019864611327648
21.0
bm25                      Weight=1.0 Best=0.000
bm25                      Weight=1.0 Best=0.218
bm25                      Weight=1.0 Best=0.222
bm25                      Weight=1.0 Best=0.222
7.241685874760151
22.0
ndcg                      Weight=1.0 Best=0.000
ndcg                      Weight=1.0 Best=0.134
ndcg                      Weight=1.0 Best=0.134
ndcg                      Weight=1.0 Best=0.134
7.37565890699625
23.0
mrr                       Weight=1.0 Best=0.000
mrr                       Weight=1.0 Best=0.148
mrr                       Weight=1.0 Best=0.148
mrr                       Weight=1.0 Best=0.148
7.523537017405033
24.0
map                       Weight=1.0 Best=0.000
map                       Weight=1.0 Best=0.093
map                       Weight=1.0 Best=0.109
map                       Weight=1.0 Best=0.109
7.732164166867733
25.0
0.30928656667470933

In [7]:
for cid in [
    "CAND_0000031",
    "CAND_0000001",
    "CAND_0000047",
    "CAND_0000050"
]:

    candidate = next(
        c for c in candidates
        if c.candidate_id == cid
    )

    score = ranker._score_evidence(job, candidate)

    print(cid, score)

CAND_0000031 0.30928656667470933
CAND_0000001 0.15569716304540634
CAND_0000047 0.10386441245675088
CAND_0000050 0.13281193122267723

In [7]:
test_candidates = [
    "CAND_0000031",
    "CAND_0000074",
    "CAND_0000001",
    "CAND_0000055",
    "CAND_0000082"
]

for cid in test_candidates:

    candidate = next(
        c for c in candidates
        if c.candidate_id == cid
    )

    score = ranker._score_evidence(
        job,
        candidate
    )

    print(f"{cid}: {score:.4f}")

retrieval systems         Weight=3.0 Best=0.000
retrieval systems         Weight=3.0 Best=0.339
retrieval systems         Weight=3.0 Best=0.369
retrieval systems         Weight=3.0 Best=0.369
1.1072203516960144
3.0
ranking systems           Weight=3.0 Best=0.000
ranking systems           Weight=3.0 Best=0.448
ranking systems           Weight=3.0 Best=0.448
ranking systems           Weight=3.0 Best=0.448
2.4500079452991486
6.0
recommendation systems    Weight=3.0 Best=0.000
recommendation systems    Weight=3.0 Best=0.501
recommendation systems    Weight=3.0 Best=0.501
recommendation systems    Weight=3.0 Best=0.501
3.953246980905533
9.0
search systems            Weight=3.0 Best=0.000
search systems            Weight=3.0 Best=0.331
search systems            Weight=3.0 Best=0.417
search systems            Weight=3.0 Best=0.417
5.204311966896057
12.0
embeddings                Weight=2.5 Best=0.000
embeddings                Weight=2.5 Best=0.101
embeddings                Weight=2.5 Best=0.101
embeddings                Weight=2.5 Best=0.149
5.595610499382019
14.5
vector databases          Weight=2.5 Best=0.000
vector databases          Weight=2.5 Best=0.215
vector databases          Weight=2.5 Best=0.235
vector databases          Weight=2.5 Best=0.235
6.182717591524124
17.0
python                    Weight=1.5 Best=0.000
python                    Weight=1.5 Best=0.148
python                    Weight=1.5 Best=0.148
python                    Weight=1.5 Best=0.176
6.446440182626247
18.5
llms                      Weight=1.5 Best=0.000
llms                      Weight=1.5 Best=0.203
llms                      Weight=1.5 Best=0.203
llms                      Weight=1.5 Best=0.203
6.7515652403235435
20.0
fine-tuning               Weight=1.0 Best=0.000
fine-tuning               Weight=1.0 Best=0.228
fine-tuning               Weight=1.0 Best=0.228
fine-tuning               Weight=1.0 Best=0.228
7.019864611327648
21.0
bm25                      Weight=1.0 Best=0.000
bm25                      Weight=1.0 Best=0.218
bm25                      Weight=1.0 Best=0.222
bm25                      Weight=1.0 Best=0.222
7.241685874760151
22.0
ndcg                      Weight=1.0 Best=0.000
ndcg                      Weight=1.0 Best=0.134
ndcg                      Weight=1.0 Best=0.134
ndcg                      Weight=1.0 Best=0.134
7.37565890699625
23.0
mrr                       Weight=1.0 Best=0.000
mrr                       Weight=1.0 Best=0.148
mrr                       Weight=1.0 Best=0.148
mrr                       Weight=1.0 Best=0.148
7.523537017405033
24.0
map                       Weight=1.0 Best=0.000
map                       Weight=1.0 Best=0.093
map                       Weight=1.0 Best=0.109
map                       Weight=1.0 Best=0.109
7.732164166867733
25.0
CAND_0000031: 0.3093
retrieval systems         Weight=3.0 Best=0.000
0.14657217264175415
3.0
ranking systems           Weight=3.0 Best=0.000
0.6356145590543747
6.0
recommendation systems    Weight=3.0 Best=0.000
0.8562182039022446
9.0
search systems            Weight=3.0 Best=0.000
1.2800329327583313
12.0
embeddings                Weight=2.5 Best=0.000
1.2830123454332352
14.5
vector databases          Weight=2.5 Best=0.000
1.4381060898303986
17.0
python                    Weight=1.5 Best=0.000
1.519457221031189
18.5
llms                      Weight=1.5 Best=0.000
1.8862325623631477
20.0
fine-tuning               Weight=1.0 Best=0.000
1.9609888717532158
21.0
bm25                      Weight=1.0 Best=0.000
2.2293479964137077
22.0
ndcg                      Weight=1.0 Best=0.000
2.3354612067341805
23.0
mrr                       Weight=1.0 Best=0.000
2.526020623743534
24.0
map                       Weight=1.0 Best=0.000
2.62885794788599
25.0
CAND_0000074: 0.1052
retrieval systems         Weight=3.0 Best=0.000
retrieval systems         Weight=3.0 Best=0.199
0.5978431105613708
3.0
ranking systems           Weight=3.0 Best=0.000
ranking systems           Weight=3.0 Best=0.107
0.9183705970644951
6.0
recommendation systems    Weight=3.0 Best=0.000
recommendation systems    Weight=3.0 Best=0.110
1.2480154037475586
9.0
search systems            Weight=3.0 Best=0.000
search systems            Weight=3.0 Best=0.244
1.9792835265398026
12.0
embeddings                Weight=2.5 Best=0.000
embeddings                Weight=2.5 Best=0.066
2.1445594392716885
14.5
vector databases          Weight=2.5 Best=0.000
vector databases          Weight=2.5 Best=0.299
2.8931511603295803
17.0
python                    Weight=1.5 Best=0.000
python                    Weight=1.5 Best=0.141
3.114917453378439
18.5
llms                      Weight=1.5 Best=0.000
llms                      Weight=1.5 Best=0.121
3.297048654407263
20.0
fine-tuning               Weight=1.0 Best=0.000
fine-tuning               Weight=1.0 Best=0.119
3.472745429724455
21.0
bm25                      Weight=1.0 Best=0.000
bm25                      Weight=1.0 Best=0.076
3.5528004430234432
22.0
ndcg                      Weight=1.0 Best=0.000
ndcg                      Weight=1.0 Best=0.086
3.639211054891348
23.0
mrr                       Weight=1.0 Best=0.000
mrr                       Weight=1.0 Best=0.061
3.6997928246855736
24.0
map                       Weight=1.0 Best=0.000
map                       Weight=1.0 Best=0.193
3.8924290761351585
25.0
CAND_0000001: 0.1557
retrieval systems         Weight=3.0 Best=0.000
retrieval systems         Weight=3.0 Best=0.026
retrieval systems         Weight=3.0 Best=0.030
retrieval systems         Weight=3.0 Best=0.078
0.2704133838415146
3.0
ranking systems           Weight=3.0 Best=0.000
ranking systems           Weight=3.0 Best=0.084
ranking systems           Weight=3.0 Best=0.089
ranking systems           Weight=3.0 Best=0.121
0.6347237527370453
6.0
recommendation systems    Weight=3.0 Best=0.000
recommendation systems    Weight=3.0 Best=0.000
recommendation systems    Weight=3.0 Best=0.000
recommendation systems    Weight=3.0 Best=0.107
0.9545649290084839
9.0
search systems            Weight=3.0 Best=0.000
search systems            Weight=3.0 Best=0.141
search systems            Weight=3.0 Best=0.141
search systems            Weight=3.0 Best=0.202
1.6265098303556442
12.0
embeddings                Weight=2.5 Best=0.000
embeddings                Weight=2.5 Best=0.000
embeddings                Weight=2.5 Best=0.000
embeddings                Weight=2.5 Best=0.047
1.7432337924838066
14.5
vector databases          Weight=2.5 Best=0.000
vector databases          Weight=2.5 Best=0.135
vector databases          Weight=2.5 Best=0.135
vector databases          Weight=2.5 Best=0.161
2.1467271372675896
17.0
python                    Weight=1.5 Best=0.000
python                    Weight=1.5 Best=0.229
python                    Weight=1.5 Best=0.229
python                    Weight=1.5 Best=0.229
2.490095667541027
18.5
llms                      Weight=1.5 Best=0.000
llms                      Weight=1.5 Best=0.128
llms                      Weight=1.5 Best=0.128
llms                      Weight=1.5 Best=0.225
2.8269776329398155
20.0
fine-tuning               Weight=1.0 Best=0.000
fine-tuning               Weight=1.0 Best=0.121
fine-tuning               Weight=1.0 Best=0.121
fine-tuning               Weight=1.0 Best=0.121
2.948444716632366
21.0
bm25                      Weight=1.0 Best=0.000
bm25                      Weight=1.0 Best=0.076
bm25                      Weight=1.0 Best=0.094
bm25                      Weight=1.0 Best=0.094
3.0459089502692223
22.0
ndcg                      Weight=1.0 Best=0.000
ndcg                      Weight=1.0 Best=0.005
ndcg                      Weight=1.0 Best=0.042
ndcg                      Weight=1.0 Best=0.132
3.1782086864113808
23.0
mrr                       Weight=1.0 Best=0.000
mrr                       Weight=1.0 Best=0.068
mrr                       Weight=1.0 Best=0.068
mrr                       Weight=1.0 Best=0.106
3.283831536769867
24.0
map                       Weight=1.0 Best=0.000
map                       Weight=1.0 Best=0.090
map                       Weight=1.0 Best=0.090
map                       Weight=1.0 Best=0.117
3.4142565429210663
25.0
CAND_0000055: 0.1366
retrieval systems         Weight=3.0 Best=0.000
retrieval systems         Weight=3.0 Best=0.204
retrieval systems         Weight=3.0 Best=0.204
0.6126900315284729
3.0
ranking systems           Weight=3.0 Best=0.000
ranking systems           Weight=3.0 Best=0.118
ranking systems           Weight=3.0 Best=0.118
0.9654100835323334
6.0
recommendation systems    Weight=3.0 Best=0.000
recommendation systems    Weight=3.0 Best=0.124
recommendation systems    Weight=3.0 Best=0.124
1.3370085060596466
9.0
search systems            Weight=3.0 Best=0.000
search systems            Weight=3.0 Best=0.243
search systems            Weight=3.0 Best=0.243
2.06728233397007
12.0
embeddings                Weight=2.5 Best=0.000
embeddings                Weight=2.5 Best=0.070
embeddings                Weight=2.5 Best=0.070
2.242157518863678
14.5
vector databases          Weight=2.5 Best=0.000
vector databases          Weight=2.5 Best=0.334
vector databases          Weight=2.5 Best=0.334
3.0761439204216003
17.0
python                    Weight=1.5 Best=0.000
python                    Weight=1.5 Best=0.152
python                    Weight=1.5 Best=0.152
3.3579262048006058
18.5
llms                      Weight=1.5 Best=0.000
llms                      Weight=1.5 Best=0.091
llms                      Weight=1.5 Best=0.115
3.6676757261157036
20.0
fine-tuning               Weight=1.0 Best=0.000
fine-tuning               Weight=1.0 Best=0.119
fine-tuning               Weight=1.0 Best=0.122
3.884941004216671
21.0
bm25                      Weight=1.0 Best=0.000
bm25                      Weight=1.0 Best=0.021
bm25                      Weight=1.0 Best=0.059
4.09504609555006
22.0
ndcg                      Weight=1.0 Best=0.000
ndcg                      Weight=1.0 Best=0.095
ndcg                      Weight=1.0 Best=0.095
4.190389312803745
23.0
mrr                       Weight=1.0 Best=0.000
mrr                       Weight=1.0 Best=0.071
mrr                       Weight=1.0 Best=0.084
4.326868139207363
24.0
map                       Weight=1.0 Best=0.000
map                       Weight=1.0 Best=0.201
map                       Weight=1.0 Best=0.201
4.528353743255138
25.0
CAND_0000082: 0.1811